import type { CommandModule } from "yargs";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";
import { checkGraphify } from "../shared/system-checks.js";

type Target = "opencode" | "cursor" | "claude" | "vscode";

export const installCommand: CommandModule = {
  command: "install",
  describe: "Install graphify-mcp-tools MCP server for your editor",
  builder: (yargs) =>
    yargs
      .option("target", {
        type: "string",
        describe: "Editor/tool to configure",
        choices: ["opencode", "cursor", "claude", "vscode"] as const,
        demandOption: true,
      })
      .option("graph", {
        type: "string",
        describe: "Path to graphify-out/ directory (default: ./graphify-out)",
      }),
  handler: async (argv) => {
    const target = argv.target as Target;
    const graphDir = (argv.graph as string) ?? "./graphify-out";

    // Check graphify prerequisite
    warnIfGraphifyMissing();

    switch (target) {
      case "opencode":
        installOpenCode(graphDir);
        break;
      case "cursor":
        installCursor(graphDir);
        break;
      case "claude":
        installClaude(graphDir);
        break;
      case "vscode":
        installVSCode(graphDir);
        break;
    }
  },
};

function warnIfGraphifyMissing(): void {
  const version = checkGraphify();
  if (version) {
    console.log(`\u2713 graphify detected (v${version})`);
    return;
  }

  console.log("");
  console.log("\u26a0  WARNING: graphify not found on this system.");
  console.log("");
  console.log("  graphify-mcp-tools serves knowledge graphs generated by graphify.");
  console.log("  Without graphify, no graph data will be available for the MCP server.");
  console.log("");
  console.log("  Install graphify:");
  console.log("    uv tool install graphifyy");
  console.log("    # or: pip install graphifyy");
  console.log("");
  console.log("  Then generate a graph:");
  console.log("    graphify .");
  console.log("");
  console.log("  Docs: https://github.com/safishamsi/graphify");
  console.log("");
}

// ---------- OpenCode ----------

function installOpenCode(graphDir: string): void {
  const configDir = resolve(process.cwd(), ".opencode");
  const configPath = join(configDir, "opencode.json");

  let config: Record<string, unknown> = {};
  if (existsSync(configPath)) {
    config = JSON.parse(readFileSync(configPath, "utf-8"));
  }

  if (!config.mcp) config.mcp = {};
  const mcp = config.mcp as Record<string, unknown>;

  mcp["graphify"] = {
    type: "local",
    command: ["npx", "-y", "graphify-mcp-tools", "mcp", "--graph", graphDir],
  };

  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });
  writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
  console.log(`\u2713 OpenCode configured: ${configPath}`);
  console.log("");
  console.log("  Added MCP server 'graphify' to .opencode/opencode.json");
  console.log("  The server will start automatically when OpenCode launches.");
}

// ---------- Cursor ----------

function installCursor(graphDir: string): void {
  const configDir = resolve(process.cwd(), ".cursor");
  const configPath = join(configDir, "mcp.json");

  let config: Record<string, unknown> = {};
  if (existsSync(configPath)) {
    config = JSON.parse(readFileSync(configPath, "utf-8"));
  }

  if (!config.mcpServers) config.mcpServers = {};
  const servers = config.mcpServers as Record<string, unknown>;

  servers["graphify"] = {
    command: "npx",
    args: ["-y", "graphify-mcp-tools", "mcp", "--graph", graphDir],
  };

  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });
  writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
  console.log(`\u2713 Cursor configured: ${configPath}`);
  console.log("");
  console.log("  Added MCP server 'graphify' to .cursor/mcp.json");
  console.log("  Restart Cursor for changes to take effect.");
}

// ---------- Claude Code ----------

function installClaude(graphDir: string): void {
  console.log("\u2713 To configure Claude Code, run:");
  console.log("");
  console.log(`  claude mcp add graphify -- npx -y graphify-mcp-tools mcp --graph ${graphDir}`);
  console.log("");
  console.log("  Claude Code manages MCP servers via its CLI.");
  console.log("  The command above registers graphify-mcp-tools as a project-level MCP server.");
}

// ---------- VS Code ----------

function installVSCode(graphDir: string): void {
  const configDir = resolve(process.cwd(), ".vscode");
  const configPath = join(configDir, "mcp.json");

  let config: Record<string, unknown> = {};
  if (existsSync(configPath)) {
    config = JSON.parse(readFileSync(configPath, "utf-8"));
  }

  if (!config.servers) config.servers = {};
  const servers = config.servers as Record<string, unknown>;

  servers["graphify"] = {
    type: "stdio",
    command: "npx",
    args: ["-y", "graphify-mcp-tools", "mcp", "--graph", graphDir],
  };

  if (!existsSync(configDir)) mkdirSync(configDir, { recursive: true });
  writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n");
  console.log(`\u2713 VS Code configured: ${configPath}`);
  console.log("");
  console.log("  Added MCP server 'graphify' to .vscode/mcp.json");
  console.log("  Ensure the GitHub Copilot extension is installed for MCP support.");
}
